-- SISTEMA DE GESTIÓN DE PERMISOS DEPORTIVOS - UNHEVAL
-- Esquema adaptado a PostgreSQL. Ejecutar en una base vacía.
-- PASO 1: ejecutar por separado, conectado a postgres y fuera de una transacción:
-- CREATE DATABASE sistema_losa WITH ENCODING 'UTF8' TEMPLATE template0;
-- PASO 2: conectar a sistema_losa y ejecutar este archivo completo.
-- En pgAdmin: seleccionar sistema_losa y abrir Query Tool.
-- Este archivo solo crea estructura; el original no contiene datos.
--
-- Diferencias a considerar al migrar datos/aplicación:
-- La colación de MySQL utf8mb4_unicode_ci no se reproduce aquí: comparar
-- mayúsculas y acentos (incluidos campos UNIQUE) puede dar otros resultados.
-- Se mantienen fechas como TIMESTAMP WITHOUT TIME ZONE: verificar la zona
-- horaria al exportar los TIMESTAMP de MySQL.
-- Tras importar IDs explícitos, reajustar cada secuencia IDENTITY.
-- PostgreSQL TIME representa una hora del día, no duraciones >24 horas.
-- No se agrega una FK polimórfica a user_sessions/password_reset_tokens:
-- user_id depende de user_type, tal como en el original.

BEGIN;

CREATE TYPE disciplinas_estado_enum AS ENUM ('Activo','Inactivo');
CREATE TYPE users_rol_enum AS ENUM ('Alumno','Docente','PersonalAdministrativo');
CREATE TYPE users_estado_enum AS ENUM ('Activo','Inactivo');
CREATE TYPE trabajadores_rol_enum AS ENUM ('Administrador','Seguridad');
CREATE TYPE trabajadores_estado_enum AS ENUM ('Activo','Inactivo');
CREATE TYPE losas_estado_enum AS ENUM ('Disponible','Mantenimiento','Inactiva');
CREATE TYPE permisos_autor_enum AS ENUM ('Usuario','Administrador');
CREATE TYPE permisos_tipo_enum AS ENUM ('Normal','Especial');
CREATE TYPE permisos_estado_enum AS ENUM ('Pendiente','Aceptado','Rechazado','Cancelado');
CREATE TYPE notificacion_tipo_enum AS ENUM ('Aceptado', 'Rechazado', 'Cancelado','Pendiente');
CREATE TYPE cola_notificaciones_tipo_canal_enum AS ENUM ('Email', 'Push', 'SMS');
CREATE TYPE cola_notificaciones_estado_enum AS ENUM ('Pendiente', 'EnProceso', 'Enviado', 'Fallido');
CREATE TYPE user_sessions_user_type_enum AS ENUM ('usuario', 'trabajador');
CREATE TYPE password_reset_tokens_user_type_enum AS ENUM ('usuario', 'trabajador');

CREATE TABLE disciplinas (
    id_d INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    estado disciplinas_estado_enum NOT NULL DEFAULT 'Activo'
);

CREATE TABLE users (
    id_u INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(15) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    rol users_rol_enum NOT NULL,
    estado users_estado_enum NOT NULL DEFAULT 'Activo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE trabajadores (
    id_t INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(8) NOT NULL UNIQUE,
    nombres VARCHAR(30) NOT NULL,
    apellido_p VARCHAR(30) NOT NULL,
    apellido_m VARCHAR(30) NOT NULL,
    rol trabajadores_rol_enum NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    telefono VARCHAR(15),
    estado trabajadores_estado_enum NOT NULL DEFAULT 'Activo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE losas (
    id_l INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    numero_l VARCHAR(2) NOT NULL UNIQUE,
    ubicacion VARCHAR(100) NOT NULL,
    dimensiones VARCHAR(100),
    superficie VARCHAR(100),
    iluminacion VARCHAR(100),
    id_d INT NOT NULL,
    estado losas_estado_enum NOT NULL DEFAULT 'Disponible',
    FOREIGN KEY (id_d) REFERENCES disciplinas(id_d)
);

CREATE TABLE imagenes (
    id_img INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    url VARCHAR(255) NOT NULL,
    id_l INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_l) REFERENCES losas(id_l)
);

CREATE TABLE archivos (
    id_arch INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_original VARCHAR(255) NOT NULL,
    nombre_unico VARCHAR(255) NOT NULL UNIQUE,
    mimetype VARCHAR(100) NOT NULL,
    url VARCHAR(255) NOT NULL,
    tamanio INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE permisos (
    id_p INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_u INT NULL,
    id_t INT NULL,
    id_t_decision INT NULL,
    autor permisos_autor_enum NOT NULL DEFAULT 'Usuario',
    tipo permisos_tipo_enum NOT NULL,
    id_arch INT NULL,
    duracion_t INT NOT NULL CHECK (duracion_t > 0),
    estado permisos_estado_enum DEFAULT 'Pendiente',
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_decision TIMESTAMP NULL,
    FOREIGN KEY (id_u) REFERENCES users(id_u),
    FOREIGN KEY (id_t) REFERENCES trabajadores(id_t),
    FOREIGN KEY (id_t_decision) REFERENCES trabajadores(id_t),
    FOREIGN KEY (id_arch) REFERENCES archivos(id_arch) ON DELETE SET NULL
);

CREATE TABLE detalle_permisos (
    id_d INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_p INT NOT NULL,
    id_l INT NOT NULL,
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    duracion INT NOT NULL CHECK (duracion > 0),
    CHECK (hora_fin > hora_inicio),
    FOREIGN KEY (id_p) REFERENCES permisos(id_p),
    FOREIGN KEY (id_l) REFERENCES losas(id_l)
);

CREATE TABLE notificacion (
    id_n INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje TEXT,
    fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tipo notificacion_tipo_enum NOT NULL,
    id_p INT,
    leido BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (id_p) REFERENCES permisos(id_p)
);

CREATE TABLE cola_notificaciones (
    id_cola INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_canal cola_notificaciones_tipo_canal_enum NOT NULL DEFAULT 'Email',
    destinatario VARCHAR(255) NOT NULL,
    asunto VARCHAR(255) NULL,
    cuerpo TEXT NOT NULL,
    estado cola_notificaciones_estado_enum NOT NULL DEFAULT 'Pendiente',
    intentos INT NOT NULL DEFAULT 0,
    ultimo_error TEXT NULL,
    fecha_envio TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE configuracion_global (
    id SMALLINT CHECK (id BETWEEN -128 AND 127) PRIMARY KEY DEFAULT 1,
    hora_min_solicitud TIME NOT NULL DEFAULT '07:00:00',
    hora_max_solicitud TIME NOT NULL DEFAULT '19:00:00',
    hora_min_apertura TIME NOT NULL DEFAULT '07:00:00',
    hora_max_apertura TIME NOT NULL DEFAULT '19:00:00',
    restriccion_hoy TIME NOT NULL DEFAULT '09:00:00',
    max_horas_semana DECIMAL(4,2) NOT NULL DEFAULT 3.00
);

CREATE TABLE dias_bloqueados (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_fecha UNIQUE (fecha)
);

CREATE TABLE user_sessions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    user_type user_sessions_user_type_enum NOT NULL,
    refresh_token_hash CHAR(64) NOT NULL UNIQUE,
    device_name VARCHAR(150),
    browser VARCHAR(80),
    operating_system VARCHAR(80),
    user_agent VARCHAR(500),
    ip_address VARCHAR(45),
    last_activity_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    user_type password_reset_tokens_user_type_enum NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX cola_notificaciones_idx_estado_intentos ON cola_notificaciones (estado, intentos);
CREATE INDEX user_sessions_idx_user_active ON user_sessions (user_id, user_type, revoked_at);
CREATE INDEX user_sessions_idx_expiry ON user_sessions (expires_at);
CREATE INDEX password_reset_tokens_idx_user ON password_reset_tokens (user_id, user_type);
CREATE INDEX password_reset_tokens_idx_expiry ON password_reset_tokens (expires_at, used_at);

-- Índices de claves foráneas. MySQL/InnoDB los crea automáticamente;
-- PostgreSQL requiere declararlos explícitamente para mantener buen rendimiento.
CREATE INDEX losas_idx_id_d ON losas (id_d);
CREATE INDEX imagenes_idx_id_l ON imagenes (id_l);
CREATE INDEX permisos_idx_id_u ON permisos (id_u);
CREATE INDEX permisos_idx_id_t ON permisos (id_t);
CREATE INDEX permisos_idx_id_t_decision ON permisos (id_t_decision);
CREATE INDEX permisos_idx_id_arch ON permisos (id_arch);
CREATE INDEX detalle_permisos_idx_id_p ON detalle_permisos (id_p);
CREATE INDEX detalle_permisos_idx_id_l ON detalle_permisos (id_l);
CREATE INDEX detalle_permisos_idx_conflicto
    ON detalle_permisos (id_l, fecha, hora_inicio, hora_fin);
CREATE INDEX notificacion_idx_id_p ON notificacion (id_p);

-- Actualizar la fecha cuando cambian otros valores de la fila.
-- Conserva updated_at si la aplicación proporciona un valor diferente.
CREATE FUNCTION actualizar_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW IS DISTINCT FROM OLD
       AND NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at THEN
        NEW.updated_at := statement_timestamp()::timestamp;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_trabajadores_updated_at
BEFORE UPDATE ON trabajadores
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_imagenes_updated_at
BEFORE UPDATE ON imagenes
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_archivos_updated_at
BEFORE UPDATE ON archivos
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trg_cola_notificaciones_updated_at
BEFORE UPDATE ON cola_notificaciones
FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

COMMIT;
