import asyncio

from sqlalchemy import text

from app.core.database import engine

STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS reportes_generados (
        id_reporte BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        periodo VARCHAR(10) NOT NULL,
        anio SMALLINT NOT NULL,
        mes SMALLINT NOT NULL DEFAULT 0,
        nombre_archivo VARCHAR(255) NOT NULL,
        s3_key VARCHAR(500) NOT NULL UNIQUE,
        content_type VARCHAR(100) NOT NULL DEFAULT 'application/pdf',
        tamanio INT NOT NULL CHECK (tamanio > 0),
        sha256 CHAR(64) NOT NULL,
        fuente_ia VARCHAR(30) NOT NULL,
        generado_por INT NULL REFERENCES trabajadores(id_t) ON DELETE SET NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT reportes_periodo_valido CHECK (periodo IN ('mensual', 'anual')),
        CONSTRAINT reportes_anio_valido CHECK (anio BETWEEN 2020 AND 2100),
        CONSTRAINT reportes_mes_valido CHECK (
            (periodo = 'mensual' AND mes BETWEEN 1 AND 12)
            OR (periodo = 'anual' AND mes = 0)
        ),
        CONSTRAINT reportes_periodo_unico UNIQUE (periodo, anio, mes)
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS reportes_generados_idx_generado_por
    ON reportes_generados (generado_por)
    """,
    "DROP TRIGGER IF EXISTS trg_reportes_generados_updated_at ON reportes_generados",
    """
    CREATE TRIGGER trg_reportes_generados_updated_at
    BEFORE UPDATE ON reportes_generados
    FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at()
    """,
)


async def migrate() -> None:
    async with engine.begin() as connection:
        for statement in STATEMENTS:
            await connection.execute(text(statement))
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(migrate())
    print("Migración de reportes en S3 aplicada correctamente")
